# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sekret < Formula
  desc "Secure your API keys in OS keychain, load them as env vars"
  homepage "https://github.com/eazyhozy/sekret"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eazyhozy/sekret/releases/download/v0.2.0/sekret_darwin_amd64.tar.gz"
      sha256 "cad3c024f95412d90230c82a91f68cde0847ffcc4aa301b8cd78f1912ea43029"

      def install
        bin.install "sekret"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eazyhozy/sekret/releases/download/v0.2.0/sekret_darwin_arm64.tar.gz"
      sha256 "d0e831ec3b8844f6ef600ea1f86caa6686c8866dc86104a5bcf10691c236e049"

      def install
        bin.install "sekret"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eazyhozy/sekret/releases/download/v0.2.0/sekret_linux_amd64.tar.gz"
      sha256 "a19dc7f8744c27ecbcef810076c50d9dceb1039f27481eb6a25dabde1524dcdb"
      def install
        bin.install "sekret"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eazyhozy/sekret/releases/download/v0.2.0/sekret_linux_arm64.tar.gz"
      sha256 "82f6fd117f4ac71605365a8cc11a028f9b7e5618dc4379143309c29f8a8d3eb9"
      def install
        bin.install "sekret"
      end
    end
  end

  test do
    system "#{bin}/sekret", "--help"
  end
end
