# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sekret < Formula
  desc "Secure your API keys in OS keychain, load them as env vars"
  homepage "https://github.com/eazyhozy/sekret"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eazyhozy/sekret/releases/download/v0.1.1/sekret_darwin_amd64.tar.gz"
      sha256 "6c14df1ad5f47337018be0af943d9465300f9b2d0830ab1c1a742b91896c0c86"

      def install
        bin.install "sekret"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eazyhozy/sekret/releases/download/v0.1.1/sekret_darwin_arm64.tar.gz"
      sha256 "aa46c85d2039be0e3095ef69af1e43db0374891ebfa024c836a7a63fbd6598f5"

      def install
        bin.install "sekret"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eazyhozy/sekret/releases/download/v0.1.1/sekret_linux_amd64.tar.gz"
      sha256 "782100ce47150d74a29b14fab0df89e150684e89f777a0739c234ff19b1d631d"
      def install
        bin.install "sekret"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eazyhozy/sekret/releases/download/v0.1.1/sekret_linux_arm64.tar.gz"
      sha256 "4d7b709bc88698a3919cd48c39e8f05ee004be2b01ae6c061cb35f03a47e1922"
      def install
        bin.install "sekret"
      end
    end
  end

  test do
    system "#{bin}/sekret", "--help"
  end
end
