# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sekret < Formula
  desc "Secure your API keys in OS keychain, load them as env vars"
  homepage "https://github.com/eazyhozy/sekret"
  version "0.1.0-test"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eazyhozy/sekret/releases/download/v0.1.0-test/sekret_darwin_amd64.tar.gz"
      sha256 "70d1e2a469b0c03f5b40743e3c40105d3082531ccb86de6d57a9ab0614dc5efa"

      def install
        bin.install "sekret"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eazyhozy/sekret/releases/download/v0.1.0-test/sekret_darwin_arm64.tar.gz"
      sha256 "3e8e03d5237add3972a145adad895d64cc850a32021993160b0ba41d3f0ae3d8"

      def install
        bin.install "sekret"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eazyhozy/sekret/releases/download/v0.1.0-test/sekret_linux_amd64.tar.gz"
      sha256 "bb6e9629cc0599ae7abaa76173a8c0c90cd49fba340fb137800c49c81e02228c"
      def install
        bin.install "sekret"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eazyhozy/sekret/releases/download/v0.1.0-test/sekret_linux_arm64.tar.gz"
      sha256 "b037b7bba2ee7261325ff2f5577704a199f11fc83cf85fbce176f4b7334ea60e"
      def install
        bin.install "sekret"
      end
    end
  end

  test do
    system "#{bin}/sekret", "--help"
  end
end
